#!/bin/sh

# We don't have eth0
uci del_list "network.@device[0].ports=eth0" 2>/dev/null || true
sed -i 's/"device": "eth0"/"device": "br-lan"/g' /etc/board.json

# Remove target-specific APK feed (msm89xx is not on downloads.openwrt.org)
sed -i '\|/targets/msm89xx/msm8916/packages|d' /etc/apk/repositories.d/distfeeds.list 2>/dev/null || true

/etc/init.d/wsdd2 enable
/etc/init.d/wsdd2 start

# System
uci set system.@system[0].hostname='OpenWRT-UZ801'

# DHCP
uci set dhcp.lan.ra='disabled'
uci set dhcp.lan.dhcpv6='disabled'
uci set dhcp.lan.ndp='disabled'
uci set dhcp.lan.ignore='0'
uci set dhcp.lan.start='100'
uci set dhcp.lan.limit='150'
uci set dhcp.lan.leasetime='5d'

# Network - LAN IP
uci set network.lan.ipaddr='192.168.2.1'
uci set network.lan.netmask='255.255.255.0'

# Firewall - keep lan open (important for USB Gadget & management)
uci set firewall.@zone[0].input='ACCEPT'
uci set firewall.@zone[0].output='ACCEPT'
uci set firewall.@zone[0].forward='ACCEPT'

# USB Gadget - always enable RNDIS for management access
uci set usbgadget.usb.enabled='1'
uci set usbgadget.rndis.enabled='1'
# Optional: also enable serial console
# uci set usbgadget.acm.enabled='1'
# uci set usbgadget.acm.shell='1'

# WiFi
/sbin/wifi config
uci set wireless.default_radio0.multicast_to_unicast='1'
uci set wireless.default_radio0.ssid='OpenWRT-UZ801'



# USB Gadget همیشه فعال
uci set usbgadget.usb.enabled='1'
uci set usbgadget.rndis.enabled='1'

# اختیاری: فعال کردن سریال هم برای بازیابی اضطراری
# uci set usbgadget.acm.enabled='1'
# uci set usbgadget.acm.shell='1'

uci commit

# Enable services
/etc/init.d/usb-gadget enable
